version: "3"
networks:
  internal:
    driver: bridge
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - internal
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:8080"
    depends_on:
      - couchdb
      - redis
    networks:
      - internal
  couchdb:
    image: couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - internal
